# Generated by Django 5.2.17 on 2026-09-08 05:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_path', models.CharField(db_index=True, max_length=512, unique=True)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('secret_hash', models.CharField(blank=True, default='', max_length=255)),
                ('language_enabled', models.BooleanField(default=True)),
                ('version_enabled', models.BooleanField(default=True)),
                ('language_label', models.CharField(blank=True, default='', max_length=255)),
                ('version_label', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['root_path'],
            },
        ),
        migrations.CreateModel(
            name='PathMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_root', models.CharField(max_length=512)),
                ('new_root', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'pending (copy/switch outstanding)'), ('switched', 'switched (old keys pending deletion)'), ('completed', 'completed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_migrations', to='registry.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LayoutChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_language_enabled', models.BooleanField()),
                ('old_version_enabled', models.BooleanField()),
                ('new_language_enabled', models.BooleanField()),
                ('new_version_enabled', models.BooleanField()),
                ('language_label', models.CharField(blank=True, default='', max_length=255)),
                ('version_label', models.CharField(blank=True, default='', max_length=255)),
                ('key_mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending (copy/switch outstanding)'), ('switched', 'switched (old keys pending deletion)'), ('completed', 'completed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_changes', to='registry.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_root', models.CharField(blank=True, default='', max_length=512)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='registry.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('commit_hash', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='registry.project')),
            ],
            options={
                'ordering': ['registered_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'language', 'version'), name='uniq_publication')],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('exact', 'exact'), ('prefix', 'prefix')], default='exact', max_length=16)),
                ('from_path', models.CharField(db_index=True, max_length=2048)),
                ('to_path', models.CharField(max_length=2048)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='registry.project')),
            ],
            options={
                'ordering': ['from_path'],
                'constraints': [models.UniqueConstraint(fields=('from_path', 'match_type'), name='uniq_redirect')],
            },
        ),
    ]
