# Generated by Django 5.2.17 on 2026-09-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutchange',
            name='created_redirect_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pathmigration',
            name='key_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
