# Generated by Django 5.2.17 on 2026-09-08 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_layoutchange_created_redirect_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('commit_hash', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('key_prefix', models.CharField(max_length=512)),
                ('manifest', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'pending (uploads outstanding)'), ('completed', 'completed (publication registered)')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='registry.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
