name: Tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build artifacts
    uses: canonical/charm-ci/.github/workflows/build-artifacts.yml@0eef5b8cbef3ee74907850f790cab64bcf0499e5  # v1.0.0
    permissions:
      actions: read
      contents: read
      packages: write
    with:
      pre-build-rock-script: >-
        uv export --frozen --no-dev --no-hashes --no-emit-project
        --format requirements.txt --output-file requirements.txt

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Run unit tests
        run: uv run pytest tests/unit -v
